controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
# home:
# # path veut dire chemin(..retour en arriere)
#     path: /
#     controller: App\Controller\HomeController::index
